# LISTS

In [1]:
List = [1, 2, 'venu', 1.30, True]
print("Elements of the list are : ")
print(List)

Elements of the list are : 
[1, 2, 'venu', 1.3, True]


In [2]:
List1 = ['venu', 'gopal', 'd', 'r']
print("first element of list : ")
print(List1[0])
print("third element of list : ")
print(List1[2])
print("last element of list : ")
print(List1[-1])
print("first element of list : ")
print(List1[-4])

first element of list : 
venu
third element of list : 
d
last element of list : 
r
first element of list : 
venu


In [3]:
List2 = [['venu', 'gopal'], 'd', 'r']
print("first list of list : ")
print(List2[0])
print("first element of list of list : ")
print(List2[0][0])
print("last element of list : ")
print(List2[-1])
print("last element of first list : ")
print(List2[0][-1])

first list of list : 
['venu', 'gopal']
first element of list of list : 
venu
last element of list : 
r
last element of first list : 
gopal


# Tuple

In [4]:
Tuple = 'venu', 'gopal'
print("elements of tuple are: ")
print(Tuple)

elements of tuple are: 
('venu', 'gopal')


In [5]:
Tuple1 = (8,)
print("one element tuple : ")
print(Tuple1)

one element tuple : 
(8,)


In [6]:
List13 = ['venu', 'gopal', 'ubdt', 'dvg']
Tuple13 = tuple(List13)
print("list to tuple : ")
print(Tuple13)
print("third element of tuple : ")
print(Tuple13[2])

list to tuple : 
('venu', 'gopal', 'ubdt', 'dvg')
third element of tuple : 
ubdt


# SET

In [7]:
Set = set(['venu', 'gopal', 'd', 'r', 'ubdt', 'dvg'])
print("Set elements are : ")
print(Set)

Set1 = {1, 2, 3, 4, 'venu'}
print("Set elements are : ")
print(Set1)

print("Set elements are : ")
for i in Set:
    print(i , end="       ")
print()
print("venu" in Set)

Set elements are : 
{'ubdt', 'dvg', 'd', 'venu', 'gopal', 'r'}
Set elements are : 
{1, 2, 3, 4, 'venu'}
Set elements are : 
ubdt       dvg       d       venu       gopal       r       
True


# Frozen Set

In [8]:
normal_set = set([1, 2, 3, 'venu', 'gopal'])
print("normal set : ")
print(normal_set)
normal_set.add(5)

frozen_set = frozenset(normal_set)
print("frozen set : ")
print(frozen_set)
# frozen_set.add('vg')

normal set : 
{1, 2, 3, 'venu', 'gopal'}
frozen set : 
frozenset({'gopal', 1, 2, 3, 5, 'venu'})


# String

In [9]:
Str = "welcome to ubdt college of engineering"
print(Str)

print(Str[0])
print(Str[-1])
print(Str[::-1])
print(Str[1:])

welcome to ubdt college of engineering
w
g
gnireenigne fo egelloc tdbu ot emoclew
elcome to ubdt college of engineering


In [10]:
# String methods
print(Str.upper())
print(Str.lower())
print(Str.title())
print(Str.capitalize())
print(Str.swapcase())
print(Str.casefold())
print(Str.zfill(0))
print(Str.isalpha())
print(Str.isnumeric())
print(Str.isdigit())
print(Str.rstrip())
print(Str.lstrip())
# print(Str.rjust())
print(Str.translate(Str))

WELCOME TO UBDT COLLEGE OF ENGINEERING
welcome to ubdt college of engineering
Welcome To Ubdt College Of Engineering
Welcome to ubdt college of engineering
WELCOME TO UBDT COLLEGE OF ENGINEERING
welcome to ubdt college of engineering
welcome to ubdt college of engineering
False
False
False
welcome to ubdt college of engineering
welcome to ubdt college of engineering
welcomeetoeubdtecollegeeofeengineering


In [11]:
String1 = "Hello, I'm a Geek"
print("Initial String: ") 
print(String1) 
  
# Deleting a String 
# with the use of del 

del String1 
print("\nDeleting entire String: ") 
print(String1)

Initial String: 
Hello, I'm a Geek

Deleting entire String: 


NameError: name 'String1' is not defined

In [12]:
Str1 = '|{:<10}|{:>10}|{:>10}|'.format('name', 'branch', 'ph no')
print(Str1)

|name      |    branch|     ph no|


# Dictionary

In [13]:
Dict = {'fname':'venu','lname':'gopal',1:[1, 2, 3, 4]}
print(Dict)

print(Dict[1])
print(Dict['fname'])
print(Dict.get('lname'))


# different ways of accesing dictionary using built-in methods

for i in Dict.keys():
    print(i,end="   ")
print()

for i in Dict.values():
    print(i, end="  ")
print()

for i in Dict.items():
    print(i, end = "  ")

{'fname': 'venu', 'lname': 'gopal', 1: [1, 2, 3, 4]}
[1, 2, 3, 4]
venu
gopal
fname   lname   1   
venu  gopal  [1, 2, 3, 4]  
('fname', 'venu')  ('lname', 'gopal')  (1, [1, 2, 3, 4])  

In [14]:
mydict = {x:x**2 for x in range(50)}
print(mydict)

{0: 0, 1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100, 11: 121, 12: 144, 13: 169, 14: 196, 15: 225, 16: 256, 17: 289, 18: 324, 19: 361, 20: 400, 21: 441, 22: 484, 23: 529, 24: 576, 25: 625, 26: 676, 27: 729, 28: 784, 29: 841, 30: 900, 31: 961, 32: 1024, 33: 1089, 34: 1156, 35: 1225, 36: 1296, 37: 1369, 38: 1444, 39: 1521, 40: 1600, 41: 1681, 42: 1764, 43: 1849, 44: 1936, 45: 2025, 46: 2116, 47: 2209, 48: 2304, 49: 2401}


# Matrix

In [15]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9],[1,4,7]])
print(a)

# changing shape of the matrix
m = a.reshape(3,4)
print("\n reshaped matrix : ")
print(m)

# accessing the elements
print("\nAccessing the elements of the matrix : ")
print(a[1])
print(a[2][0])

# adding to the matrix
m = np.append(m,[[2,5,8,9]],0)
print("\nAdding item to matrix : ")
print(m)

# deleting from the matrix
m = np.delete(m,[-1],0)
print("\nDeleting item from the matrix : ")
print(m)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 4 7]]

 reshaped matrix : 
[[1 2 3 4]
 [5 6 7 8]
 [9 1 4 7]]

Accessing the elements of the matrix : 
[4 5 6]
7

Adding item to matrix : 
[[1 2 3 4]
 [5 6 7 8]
 [9 1 4 7]
 [2 5 8 9]]

Deleting item from the matrix : 
[[1 2 3 4]
 [5 6 7 8]
 [9 1 4 7]]


# ByteArray

In [16]:
b = bytearray((16, 8, 3, 25))
print("after creating : ")
print(b)

print("accessing elements : ")
print(b[1])

b.append(2)
print("after adding element : ")
print(b)

b[0] = 90
print("after modifying : ")
print(b)

after creating : 
bytearray(b'\x10\x08\x03\x19')
accessing elements : 
8
after adding element : 
bytearray(b'\x10\x08\x03\x19\x02')
after modifying : 
bytearray(b'Z\x08\x03\x19\x02')


# Linked List

In [17]:
# simple implementation of linked list of empty head
class node:
    def __init__(self, data):
        self.data = data
        self.next = None

class LList:
    def __init__(self):
        self.head = None

In [18]:
# creating a linked list of 3 nodes connected
class node:
    
    def __init__(self, data):
        self.data = data
        self.next = None

class LList:
    
    def __init__(self):
        self.head = None
        
if __name__ == '__main__':
    ll = LList()
    ll.head = node(1)
    second = node(2)
    third = node(3)
    
    ll.head.next = second
    second.next = third

In [19]:
class Node:
    def __init__(self, data):
        self.data = data
        self.next = None
        
class LList:
    def __init__(self):
        self.head = None
    
    def printList(self):
        temp = self.head
        while (temp):
            print (temp.data)
            temp = temp.next
            
if __name__ == '__main__':
    ll = LList()
    ll.head = Node(5)
    second = Node(7)
    third = Node(9)
    
    ll.head.next = second;
    second.next = third;
    
    ll.printList()

5
7
9


# inserting a new node at beginning of the linked list    -> o(1)

In [20]:
class Node:
    def __init__(self, data):
        self.data = data
        self.next = None
        
class LList:
    def __init__(self):
        self.head = None
        
    def printList(self):
        temp = self.head
        while(temp):
            print(temp.data)
            temp = temp.next
            
    def push(self, new_data):
        new_node = Node(new_data)
        new_node.next = self.head
        self.head = new_node

if __name__ == '__main__':
    ll = LList()
    ll.head = Node(1)
    second = Node(3)
    third = Node(2)
    four = Node(3)
    
    ll.head.next = second
    second.next = third
    third.next = four
    
    print("Before insertion : ")
    ll.printList()
    ll.push(1323)
    print("After insertion : ")
    ll.printList()

Before insertion : 
1
3
2
3
After insertion : 
1323
1
3
2
3


# inserting a new node at the end of the linked list    -> o(n)

In [26]:
class Node:
    def __init__(self, data):
        self.data = data
        self.next = None
        
class LList:
    def __init__(self):
        self.head = None
        
    def printList(self):
        temp = self.head
        while(temp):
            print(temp.data)
            temp = temp.next
    
    def Append(self, new_data):
        new_node = Node(new_data)
        
        if self.head is None:
            head.next = new_node
            return
        
        last = self.head
        while(last.next):
            last = last.next
        last.next = new_node
        
if __name__ == '__main__':
    ll = LList()
    ll.head = Node(13)
    second = Node(23)
    third = node(11)
    ll.head.next = second
    second.next = third
    
    print("Before insertion : ")
    ll.printList()
    ll.Append(1323)
    print("After insertion : ")
    ll.printList()

Before insertion : 
13
23
11
After insertion : 
13
23
11
1323


# inserting a new node after given node of the linked list    -> o(1)

In [25]:
class Node:
    def __init__(self, data):
        self.data = data
        self.next = None
class LList:
    def __init__(self):
        self.head = None
        
    def printList(self):
        temp = self.head
        while(temp):
            print(temp.data)
            temp = temp.next
        
    def insertAt(self, prev_node, new_data):
        if prev_node is None:
            print("Node must be in linked list!!")
            return
        new_node = Node(new_data)
        new_node.next = prev_node.next
        prev_node.next = new_node
        
if __name__ == '__main__':
    ll = LList()
    ll.head = Node(13)
    second = Node(23)
    third = Node(11)
    
    ll.head.next = second
    second.next = third
    
    print("Before insertion : ")
    ll.printList()
    ll.insertAt(second, 90)
    print("After insertion : ")
    ll.printList()

Before insertion : 
13
23
11
After insertion : 
13
23
90
11


# Deletion of node from beginning

In [17]:
class Node:
    def __init__(self, data):
        self.data = data
        self.next = None
class LList:
    def __init__(self):
        self.head = None
        
    def printList(self):
        temp = self.head
        while(temp):
            print(temp.data)
            temp = temp.next
        
    def insertAt(self, prev_node, new_data):
        if prev_node is None:
            print("Node must be in linked list!!")
            return
        new_node = Node(new_data)
        new_node.next = prev_node.next
        prev_node.next = new_node
        
    def Delete(self):
        temp = self.head
        self.head = self.head.next
        del temp
        
if __name__ == '__main__':
    ll = LList()
    ll.head = Node(13)
    second = Node(23)
    third = Node(11)
    
    ll.head.next = second
    second.next = third
    
    print("Before deletion : ")
    ll.printList()
    ll.Delete()
    print("After deletion : ")
    ll.printList()

Before deletion : 
13
23
11
After deletion : 
23
11


# Delete the node from the linked list by given position

In [9]:
class node:
    def __init__(self, data):
        self.data = data
        self.next = None
        
class LList:
    def __init__(self):
        self.head = None
        
    def printList(self):
        temp = self.head
        while(temp):
            print(temp.data)
            temp = temp.next
            
    def push(self, new_data):
        new_node = Node(new_data)
        new_node.next = self.head
        self.head = new_node
        
    def DeleteAt(self, pos):
        if self.head is None:
            return
        
        index = 0
        current = self.head
        while current.next and index < pos:
            prev = current
            current = current.next
            index+=1
        if index < pos:
            print("index out of range!!")
        elif index == 0:
            self.head = self.head.next
        else:
            prev.next = current.next
            current = None
        
if __name__ == '__main__':
    ll = LList()
    ll.push(11)
    ll.push(13)
    ll.push(23)
    ll.push(33)
    ll.push(43)
    print("Before deletion : ")
    ll.printList()
    ll.DeleteAt(3)
    print("After deletion : ")
    ll.printList()

Before deletion : 
43
33
23
13
11
After deletion : 
43
33
23
11


# Get count of no of nodes in linked list

In [16]:
class Node:
    def __init__(self, data):
        self.data = data
        self.next = None
        
class LList:
    def __init__(self):
        self.head = None
    
    def printList(self):
        temp = self.head
        while (temp):
            print (temp.data)
            temp = temp.next
            
    def getcount(self):
        temp = self.head
        count = 0
        while(temp):
            count+=1
            temp = temp.next
        return count
            
if __name__ == '__main__':
    ll = LList()
    ll.head = Node(5)
    second = Node(7)
    third = Node(9)
    
    ll.head.next = second;
    second.next = third;
    
    ll.printList()
    print("number of nodes in the given linked list are :%d " % ll.getcount())

5
7
9
number of nodes in the given linked list are :3 


In [2]:
class Node:
    def __init__(self, data):
        self.data = data
        self.next = None
        
class LList:
    def __init__(self):
        self.head = None
    
    def printList(self):
        temp = self.head
        while (temp):
            print (temp.data)
            temp = temp.next
            
    def getcount(self):
        temp = self.head
        count = 0
        while(temp):
            count+=1
            temp = temp.next
        return count
    
    def search(self, x):
        temp = self.head
        v = []
        while(temp):
            v.append(temp.data)
            temp = temp.next
        if x in v:
            return True
        else:
            return False
        
    def reverse(self):
        prev = None
        current = self.head
        while(current is not None):
            next = current.next
            current.next = prev
            prev = current
            current = next
        self.head = prev
            
if __name__ == '__main__':
    ll = LList()
    ll.head = Node(5)
    second = Node(7)
    third = Node(9)
    
    ll.head.next = second;
    second.next = third;
    
    print(ll.search(7))
    ll.printList()
    print("number of nodes in the given linked list are :%d " % ll.getcount())
    ll.reverse()
    ll.printList()

True
5
7
9
number of nodes in the given linked list are :3 
9
7
5


In [ ]:
def reverse(self):
        prev = None
        current = self.head
        while(current is not None):
            next = current.next
            current.next = prev
            prev = current
            current = next
        self.head = prev

# Stack

In [14]:
class stack:
    def __init__(self):
        self.stack = []
        
    def pushele(self, val):
        self.stack.append(val)
        
    def delete(self):
        print(self.stack.pop())
        
    def display(self):
        for self.x in self.stack:
            print(self.x)
            
obj = stack()
obj.pushele(1)
obj.pushele(4)
obj.pushele(9)
obj.pushele(16)
obj.pushele(25)
obj.pushele(36)

print("elements of the stack are : ")
obj.display()

print("popped element is : ")
obj.delete()

print("elements after pop are : ")
obj.display()

obj.pushele(49)
print("elements after push : ")
obj.display()

elements of the stack are : 
1
4
9
16
25
36
popped element is : 
36
elements after pop are : 
1
4
9
16
25
elements after push : 
1
4
9
16
25
49


# infix to postfix using stack

In [6]:
def prec(c):
    if c == '^':
        return 3
    elif c == '*' or c == '/':
        return 2
    elif c == '+' or c == '-':
        return 1
    else:
        return -1
    
def associativity(c):
    if c == '^':
        return 'R'
    return 'L'

def infix_to_postfix(s):
    result = []
    stack = []
    
    for i in range(len(s)):
        c = s[i]
        if 'a'<= c >= 'z' or 'A' <= c >= 'Z' or '0' <= c >= '9':
            result.append(c)
            
        elif c == '(':
            stack.append(c)
            
        elif c == ')':
            while stack and stack[-1] != '(':
                result.append(stack.pop())
            stack.pop() #( -> pop
            
        else:
            while stack and (prec(s[i]) < prec(stack[-1]) or (prec(s[i]) == prec(stack[-1]) and associativity(s[i]) == 'L')):
                result.append(stack.pop())
            stack.append(c)
            
    while stack:
        result.append(stack.pop())
        
    print(''.join(result))
    
exp = "((A+B)-C*(D/E))+F"
infix_to_postfix(exp)

AB+CDE/*-F+


# prefix to infix

In [11]:
def prefix_to_infix(s):
    stack = []
    i = len(s) - 1
    while i >= 0:
        if not isOperator(s[i]):
            stack.append(s[i])
            i-=1
        else:
            str1 = '(' + stack.pop() + s[i] + stack.pop() + ')'
            stack.append(str1)
            i-=1
            
    return stack.pop()

def isOperator(c):
    if c == '+' or c == '-' or c == '*' or c == '/' or c == '^' or c == '(' or c ==')':
        return True
    return False

if __name__ == '__main__':
    exp = '*-A/BC-/AKL'
    print(prefix_to_infix(exp))  #((A-(B/C))*((A/K)-L))

((A-(B/C))*((A/K)-L))


# prefix to postfix

In [18]:
def prefix_to_postfix(s):
    stack = []
    i = len(s) - 1
    while i >= 0:
        if not isoperator(s[i]):
            stack.append(s[i])
            i-=1
        else:
            str1 = stack.pop() + stack.pop() + s[i]
            stack.append(str1)
            i-=1
    return stack.pop()
def isoperator(c):
    if c == '+' or c == '-' or c == '/' or c == '*' or c == '^' or c == '(' or c == ')':
        return True
    return False

if __name__ == '__main__':
    exp = '*-A/BC-/AKL'
    print(prefix_to_postfix(exp))

ABC/-AK/L-*


# postfix to prefix

In [15]:
def postfix_to_prefix(s):
    stack = []
    for i in range(len(s)):
        if not isoperator(s[i]):
            stack.append(s[i])
        else:
            op1 = stack[-1]
            stack.pop()
            op2 = stack[-1]
            stack.pop()
            str1 = s[i]+op2+op1
            stack.append(str1)
    return stack.pop()
def isoperator(c):
    if c == '+' or c == '-' or c == '*' or c == '/' or c == '^' or c == '(' or c == ')':
        return True
    return False
if __name__ == '__main__':
    exp = "AB+CD-*"
    print(postfix_to_prefix(exp))

*+AB-CD


# postfix to infix

In [19]:
def postfix_to_infix(s):
    stack = []
    for i in range(len(s)):
        if not isoperator(s[i]):
            stack.append(s[i])
        else:
            op1 = stack[-1]
            stack.pop()
            op2 = stack[-1]
            stack.pop()
            str1 = '(' + op2 + s[i] + op1 + ')'
            stack.append(str1)
    return stack.pop()
def isoperator(c):
    if c == '+' or c == '-' or c == '*' or c == '/' or c == '^' or c == '(' or c == ')':
        return True
    return False

if __name__ == '__main__':
    exp = "ABC/-AK/L-*"
    print(postfix_to_infix(exp))

((A-(B/C))*((A/K)-L))


# check for balanced brackets in an expression (well-formedness)

In [8]:
def isBalanced(s):
    stack = []
    for ch in s:
        if ch == '(' or ch == '{' or ch == '[':
            stack.append(ch)
        else:
            if stack and ((stack[-1] == '(' and ch == ')') or (stack[-1] == '{' and ch == '}') or (stack[-1] == '[' and ch == ']')):
                stack.pop()
            else:
                return False
    return not stack

exp = "{()[}]"

if isBalanced(exp):
    print("balanced ")
else:
    print("not balanced")

not balanced


# evaluate postfix expression

In [28]:
def isoperator(char):
    return char in ['+', '-', '*', '/']

def post_to_infix(s):
    stack = []
    for i in range(len(s)):
        if not isoperator(s[i]):
            stack.append(s[i])
        else:
            op1 = stack[-1]
            stack.pop()
            op2 = stack[-1]
            stack.pop()
            if s[i] == '+':
                stack.append(int(op2) + int(op1))
            elif s[i] == '-':
                stack.append(int(op2) - int(op1))
            elif s[i] == '*':
                stack.append(int(op2) * int(op1))
            elif s[i] == '+/':
                stack.append(int(op2) // int(op1))
    return stack.pop()
exp = "231*+9-"
post_to_infix(exp)

-4

# reverse string using stack

In [17]:
def reverse(s):
    stack = []
    l = len(s)
    for i in range(l):
        stack.append(s[i])
    s = ""
    while stack:
        s+=stack.pop()
        
    return s

string = "venugopal d r"
print(reverse(string))

r d lapogunev


# print second largest element

In [19]:
def find_second_largest(arr):
    # Initialize first and second largest elements
    first_max = second_max = float('-inf')

    # Traverse the list
    for num in arr:
        # Update first_max if current element is greater
        if num > first_max:
            second_max = first_max
            first_max = num
        # Update second_max if current element is greater than second_max
        elif num > second_max and num != first_max:
            second_max = num

    # Check if second_max is updated
    if second_max == float('-inf'):
        return "There is no second largest element."
    else:
        return second_max

# Example usage:
my_list = [10, 20, 4, 45, 99]
print("Second largest element:", find_second_largest(my_list))


Second largest element: 45


# Queue

In [27]:
class queue:
    def __init__(self):
        self.queue = []
    def push(self, ele):
        self.queue.append(ele)
    def popq(self):
        print(self.queue.pop(0))
    def display(self):
        for i in self.queue:
            print(i)
            
obj = queue()
obj.push(1)
obj.push(2)
obj.push(3)
obj.push(4)
obj.push(5)

print("elements after pushing elements into queue : ")
obj.display()

print("element popped from queue : ")
obj.popq()

print("elements in queue after popping : ")
obj.display()

obj.push(10)
print("elements in queue after pushing : ")
obj.display()

elements after pushing elements into queue : 
1
2
3
4
5
element popped from queue : 
1
elements in queue after popping : 
2
3
4
5
elements in queue after pushing : 
2
3
4
5
10


# Priority Queue

In [30]:
# A simple implementation of Priority Queue using Queue.

class PriorityQueue:
    
    def __init__(self):
        self.queue = []
        
    def __str__(self):
        return ' '.join([str(i) for i in self.queue])

# for checking if the queue is empty
    def isEmpty(self):
        return len(self.queue) == 0

# for inserting an element in the queue
    def insert(self, data):
        self.queue.append(data)

# for popping an element based on Priority
    def delete(self):
        try:
            max = 0
            for i in range(len(self.queue)):
                if self.queue[i] > self.queue[max]:
                    max = i
            item = self.queue[max]
            del self.queue[max]
            return item
        except IndexError:
            print()
            exit()

if __name__ == '__main__':
    myQueue = PriorityQueue()
    myQueue.insert(12)
    myQueue.insert(1)
    myQueue.insert(14)
    myQueue.insert(7)
    print(myQueue)
    while not myQueue.isEmpty():
        print(myQueue.delete())


12 1 14 7
14
12
7
1
